### ISSUE TITLE
Cascade truncated

### ISSUE THREAD

**Issue by eboileau** [dieterich-lab/scimodom#103]
### A clear and concise description of what the bug is.

The technology now appears truncated in `FormCascade` in `ProjectMetadata.vue`

![meta](https://github.com/dieterich-lab/scimodom/assets/32674263/5c7de158-8f97-4204-a93c-53b2ec629bcd)

**Comment by HaraldWilhelmi** [comment]
First look at it:
* The size seems to be tagged to ul element ariund the list via the class sm:w-48.
* That one says: "width: 12rem;". If that setting is disabled manually in the browser the element becomes huge.
* Most likely we want "width: fit-content;" instead.

**Comment by HaraldWilhelmi** [comment]
While this should be trivial to fix with classic CSS the PrimVue component seems not to support it.
There seems to be something called "panel", which is either only used for the first level of pull down menus
(which we don't want to change!) or all of them.

**Comment by eboileau** [comment]
Ok, I can have a look next week. This is typically handled with this [pt property](https://tailwind.primevue.org/guides/overriding-presets/). In our case, we also have defined presets (/client/src/presets/windscm/).

**Comment by HaraldWilhelmi** [comment]
Already tried pretty much everything with PassThrough - but it just did not do anything for me (style, class, as string, as  object ...)

**Comment by eboileau** [comment]
The element to pass to `pt` is  `sublist: { class: 'w-full sm:w-80' }` in `FormCascade.vue`, whereas the preset has `'w-full sm:w-48'`. This also makes the cascade a bit longer in general *e.g.* for organism in dataset upload, but I think we just leave it for now, and go back to it in Q3 when harmonizing styles throughout, see https://github.com/dieterich-lab/scimodom/issues/99.
