### ISSUE TITLE
Wrong directory permission on deployment

### ISSUE THREAD

**Issue by eboileau** [dieterich-lab/scimodom#116]
### A clear and concise description of what the bug is.

On deployment, `__create_local_folders.py` is run, and directories under `HOST_DATA_DIR` end up with the wrong ownership. This is "commented out" in the installation playbook.  `mini_cron.sh` should also be more forgiving. 

This can be fixed after install, but ideally we want a clean install.

**Comment by eboileau** [comment]
The only tricky one is `IMPORT_DIR`, which should exists on startup... see also #126

**Comment by HaraldWilhelmi** [comment]
As discussed with Etienne:
* Whenever possible SCI-MODOM should create missing directories. Setting them up is the responsibility of the FileService. That should be done by now.
* The little housekeeping job (mini-cron.sh) running in the container outside of Flask should silently ignore directories, which have not been created yet. This is a TODO.

**Comment by HaraldWilhelmi** [comment]
Etienne pointed out that we should also move out as much as possible from docker/scripts/__create_local_folders.py.
What needs to stay?
* Everything needed by the docker-compose.yml (HOST_SECRETS_DIR, HOST_IMPORT_DIR, HOST_DATA_DIR, HOST_BACKUP_DIR, HOST_CONFIG_DIR, HOST_DB_DATA_DIR)
* Everything needed by the script itself (HOST_SECRETS_DIR, HOST_CONFIG_DIR)
