### ISSUE TITLE
Delay between project creation and data upload will blow up the server

### ISSUE THREAD

**Issue by eboileau** [dieterich-lab/scimodom#117]
### Aims/objectives.

Adding a new selection on project creation will make this selection available *e.g.* for the Search, but if no data is added, this will blow up *e.g.* when trying to fetch the gene cache.

### A clear and concise description of todo items.

I don't know how to handle this... temporarily, we can find all "weak" end-points and add exception handling...

**Comment by HaraldWilhelmi** [comment]
There are multiple issues we may run into:

* Genecache not present (FileNotFoundError when accessing /genes)
* No assembly for taxa_id (NoResultFound when accessing /chroms)
* No annoation (KeyError on RNA_TYPE_TO_ANNOTATION_SOURCE_MAP when accessing /annotation)

**Comment by eboileau** [comment]
> No assembly for taxa_id (NoResultFound when accessing /chroms)

While it make sense to handle such cases, if a user is able to choose a selection, then the corresponding assembly exists, so there is in principle no problem, but this is not necessarily the case if we use the API directly. 

> No annoation (KeyError on RNA_TYPE_TO_ANNOTATION_SOURCE_MAP when accessing /annotation)

Same as above, the `rna_type` is pre-defined, but...

So yes, in general, these exceptions should be handled in *scimodom/api/utilities.py*
