### ISSUE TITLE
Table filters AND/OR

### ISSUE THREAD

**Issue by eboileau** [dieterich-lab/scimodom#137]
### A clear and concise description of todo items.

Can we _e.g._ select 2 technologies (Browse)?

**Comment by eboileau** [comment]
Please use "Match Any", and NOT "Match All", see _e.g._
![search_opts](https://github.com/user-attachments/assets/366fbc47-d379-4157-b1db-d1ee7f756f30)

**Comment by CDieterich** [comment]
Looks good to me - thank you.
