### ISSUE TITLE
Upload more data

### ISSUE THREAD

**Issue by eboileau** [dieterich-lab/scimodom#81]
### Aims/objectives.

We currently have BID-seq, eTAM-seq, and GLORI, amounting to a total of 65 dataset. We need to add more data from the public domain, esp. if we aim for a publication. We cannot rely on RMaP members to "fill" the database. I expect anyway that most users will not have data in the bedRMod format to start with.

### A clear and concise description of todo items.

- [ ] Create a list of dataset @CDieterich 
- [ ] Contact AB to generate bedRMod files, according to the [Sci-ModoM specs](https://dieterich-lab.github.io/scimodom/database.html) (in particular check *Attention* boxes).
- [ ] Check the status of bedRMod-tools? Can RMaP members eventually use it to generate data for SCIMODOM?

**Comment by CDieterich** [comment]
1: Baek A, Lee GE, Golconda S, Rayhan A, Manganaris AA, Chen S, Tirumuru N, Yu H, Kim S, Kimmel C, Zablocki O, Sullivan MB, Addepalli B, Wu L, Kim S. Single- molecule epitranscriptomic analysis of full-length HIV-1 RNAs reveals functional roles of site-specific m6As. Nat Microbiol. 2024 Apr 11. doi: 10.1038/s41564-024-01638-5. Epub ahead of print. PMID: 38605174.

2: Dai Q, Ye C, Irkliyenko I, Wang Y, Sun HL, Gao Y, Liu Y, Beadell A, Perea J, Goel A, He C. Ultrafast bisulfite sequencing detection of 5-methylcytosine in DNA and RNA. Nat Biotechnol. 2024 Jan 2. doi: 10.1038/s41587-023-02034-w. Epub ahead of print. PMID: 38168991.

3: Hartstock K, Kueck NA, Spacek P, Ovcharenko A, Hüwel S, Cornelissen NV, Bollu A, Dieterich C, Rentmeister A. MePMe-seq: antibody-free simultaneous m6A and m5C mapping in mRNA by metabolic propargyl labeling and sequencing. Nat Commun. 2023 Nov 7;14(1):7154. doi: 10.1038/s41467-023-42832-z. PMID: 37935679; PMCID: PMC10630376.

4: Chen L, Zhang LS, Ye C, Zhou H, Liu B, Gao B, Deng Z, Zhao C, He C, Dickinson BC. Nm-Mut-seq: a base-resolution quantitative method for mapping transcriptome- wide 2'-O-methylation. Cell Res. 2023 Sep;33(9):727-730. doi: 10.1038/s41422-023-00836-w. Epub 2023 Jun 15. PMID: 37316584; PMCID: PMC10474006.

**Comment by CDieterich** [comment]
@eboileau - it is hard to find these data sets via PubMed. I wonder how we should search for them

**Comment by CDieterich** [comment]
I guess it would also make a lot of sense to walk through the latest review papers such as:
https://pubs.acs.org/doi/10.1021/acs.accounts.3c00532

**Comment by CDieterich** [comment]
just in case we dont have that yet: https://pubmed.ncbi.nlm.nih.gov/35288668/

**Comment by eboileau** [comment]
This is not the end of the story...
