### ISSUE TITLE
Title truncated

### ISSUE THREAD

**Issue by eboileau** [dieterich-lab/scimodom#88]
### A clear and concise description of what the bug is.

After fa4085b20811e9c4ed7f37eddc06185cb5f70c1a (see client/src/components/ui/StyledHeadline.vue), some words appear truncated, see _e.g._ the "e" from Browse

![title](https://github.com/dieterich-lab/scimodom/assets/32674263/ce3c671b-a532-46ce-8863-c450c36e1c7a)

### What browser were you using?

Firefox

### What version of Sci-ModoM were you using?

dev

**Comment by HaraldWilhelmi** [comment]
Fixed by maxing the space after the first word a "non-breacking space" and moving it into styled span.
